### ISSUE TITLE
Random squawks from range

### ISSUE THREAD

**Issue by RaeN1** [kusterjs/CCAMS#16]
Hey,
would it be possible to have the server return a random available squawk from the range rather than the (numerically) first one available?

**Comment by kusterjs** [comment]
Definitely technically possible. But there is not really a reason to do so because of the centralisation. Random squawks by ES are simply used to reduce the likelyhood of duplicates. But this is avoided by the architecture of the server providing the codes. So why would you prefer random squawks over sorted ones?
Also, I don't know any systems from RL that assigns random squawks. The all start assigning codes in ascending order.

**Comment by kusterjs** [comment]
Currently no reasoning exists to demonstrate improved user experience and/or system stability by adding such a function. It is therefore not planned to put effort into this request and it is closed for the time.
