### ISSUE TITLE
Remove filed Equipent check

### ISSUE THREAD

**Issue by erikwachters** [kusterjs/CCAMS#32]
Hi,

Can you please consider removing the check of equipent filed by the pilot.
A lot of pilots have no clue what the equipment field is and a lot of them just leave it empty. Due to the fact that ModeS transponder is mandatory almost everywhere in the CCAMS area it's maybe not a bad idea to just remove that check on EQ.
An other idea is that you do a check on Requested FL. If the RFL is above FL195 you can be sure that the airplane is ModeS capable even if the equipment is empty or wrong.

Thanks!

Erik

**Comment by kusterjs** [comment]
What specific changes to the users of the plugin do you expect from such a change?

**Comment by kusterjs** [comment]
Thanks for the background, @erikwachters. The use of the equipment codes is an essential part of the logic of this plugin. Disabling it will render most of its functionality useless. Even the default ES logic uses equipment codes. So just assigning squawk 1000 (as your neighbour appartenlty does) regardless of the equipment could even be rated as a violation of the squawk assignment scheme. I suggest a resolution via VATEUD in this case.
Although I don't like to say this, but the change you are asking for can be done easily by no longer using this plugin. Because all other methods or plugins I'm aware of use at least some basic logic to determine whether squawk 1000 can be assigned.
I think you are aware that code assignment depends on many more factors than just the equipment (which I try to consider as good as possible with my plugin). Therefore, it is not appropriate to assign 1000 to any IFR traffic. It's always fine to assign a discrete code, for many different reasons.
