### ISSUE TITLE
Menu option "delete assigned SQ"

### ISSUE THREAD

**Issue by Phil061995** [kusterjs/CCAMS#49]
It would be great to have a menu option to delete an assigned squawk if necessary.

**Comment by kusterjs** [comment]
I can look into this. But I'm also interested why you would want to remove an assigned code, and if you expect this to influence the server-based code management.

**Comment by Phil061995** [comment]
In real life at EDDF the SQ will be assigned with clearance request. As the clearance received flag will not by synct when a new controller comes online, I'm currently testing to assign the SQ only with clearance. 

We also use the SQ so show the other controllers (e.g. when working with a coordinator), this flightplan is checked and everything is set, the clearance can be issued.

Some outbounds connect with an assigned SQ already (e.g. the one from the flight before), or I have assigned a SQ for someone not ready for the clearance or flightplan not checked. Then it would be nice to have the option to delete the assigned SQ.

**Comment by kusterjs** [comment]
Unfortunately, the plugin environment does not allow to delete an assigned code. There is no specific function for this, and sending an empty string is not accepted (the function returns false). I can only set other specific codes.
@Phil061995 So I cannot implement your request due to existing limitations. Any other solution I may help you with to solve your problem?
